#!/bin/bash
# shellcheck disable=SC1091
source common.sh
# for DSP
resources=("datasciencepipelinesapplications")
# depedent resources from kubeflow
resources+=("scheduledworkflows")
# depedent resources from argo
resources+=("clusterworkflowtemplates" "cronworkflows" "workfloweventbindings" "workflows" "workflowtaskresults" "workflowtemplates" "workflowtasksets" "workflowartifactgctasks")

nslist=$(get_all_namespace "${resources[@]}")

run_mustgather "${nslist[@]}"
