#!/bin/bash
# shellcheck disable=SC1091
source common.sh
resources=("modelregistries")
# depedent resources ossm
resources+=("smcp" "smm" "smmr" "authorizationpolicies" "destinationrules" "gateways" "virtualservices")
# depedent resources authorino
resources+=("authconfigs" "authorinos")

nslist=$(get_all_namespace "${resources[@]}")

run_mustgather "${nslist[@]}"
