#!/bin/bash
# shellcheck disable=SC1091
: "${SCRIPT_DIR:=$(dirname "$0")}"
source "${SCRIPT_DIR}/common.sh"

# MaaS core CRDs
resources=("maasmodelrefs.maas.opendatahub.io" "maasauthpolicies.maas.opendatahub.io" "maassubscriptions.maas.opendatahub.io" "externalmodels.maas.opendatahub.io")

nslist=$(get_all_namespace "${resources[@]}")

run_mustgather "$nslist" "${resources[@]}"
