#!/bin/bash
# shellcheck disable=SC1091
source common.sh
resources=("inferenceservices" "inferencegraphs" "trainedmodels" "servingruntimes" "clusterstoragecontainers" "predictors" "localmodelnodegroups")
# Dependent resources authorino
resources+=("authconfigs" "authorinos" "authpolicies.kuadrant.io")
# Dependent resources NIM
resources+=("accounts.nim.opendatahub.io")
# Dependent resources llm-d
resources+=("llminferenceserviceconfigs" "llminferenceservices" "leaderworkersetoperators" "gatewayclasses" "gateways.gateway.networking.k8s.io" "httproutes" "inferencepools" "envoyfilters")

nslist=$(get_all_namespace "${resources[@]}")

run_mustgather "${nslist[@]}"
