#!/bin/bash
# shellcheck disable=SC1091
source common.sh
resources=("admissionchecks" "clusterqueues" "localqueues" "multikueueclusters" "multikueueconfigs" "provisioningrequestconfigs" "resourceflavors" "workloads" "workloadpriorityclasses")

nslist=$(get_all_namespace "${resources[@]}")

run_mustgather "${nslist[@]}"
