#!/bin/bash
# shellcheck disable=SC1091
source common.sh
resources=("inferenceservices" "inferencegraphs" "trainedmodels" "servingruntimes" "clusterstoragecontainers" "predictors")

nslist=$(get_all_namespace "${resources[@]}")

run_mustgather "${nslist[@]}"
