#!/bin/bash
# shellcheck disable=SC1091
source common.sh
resources=("odhdashboardconfigs" "acceleratorprofiles" "hardwareprofiles.dashboard.opendatahub.io" "odhapplications" "odhdocuments" "odhquickstarts")

nslist=$(get_all_namespace "${resources[@]}")

run_mustgather "$nslist" "${resources[@]}"

