#!/bin/bash
# shellcheck disable=SC1091
source common.sh
resources=("mpijobs" "paddlejobs" "pytorchjob" "tfjob" "xgboostjob" "jaxjobs")

nslist=$(get_all_namespace "${resources[@]}")

run_mustgather "${nslist[@]}"

