#!/bin/bash
# shellcheck disable=SC1091
source common.sh
resources=("lmevaljobs" "trustyaiservices.trustyai.opendatahub.io" "guardrailsorchestrators")

nslist=$(get_all_namespace "${resources[@]}")

run_mustgather "$nslist" "${resources[@]}"
