# To get kubectl CLI (1.33.3)
FROM registry.redhat.io/openshift4/ose-cli-rhel9@sha256:b36a4c332f05bd71c5315b6cfe38987809bae09c2865217e1c7240fa6bfd813b AS builder
FROM registry.redhat.io/openshift4/ose-must-gather-rhel9:v4.21@sha256:6d458aa959871d31c3b4e787b5c981e409acf9f43ac3dcd61c8c2bec3afedf38
# copy original gather from base image to gather_original
RUN mv /usr/bin/gather /usr/bin/gather_original
# Copy kubectl from builder stage
COPY --from=builder /usr/bin/kubectl /usr/bin/kubectl
# Copy helm CLI (v4.1.4) from build context (tracked via Git LFS)
COPY bin/helm /usr/local/bin/helm
# copy all collection scripts to /usr/bin, including gather and subdirectories
COPY collection-scripts /usr/bin
# oc adm must-gather expects /usr/bin/gather
RUN mv /usr/bin/gather.sh /usr/bin/gather

ENTRYPOINT ["/usr/bin/gather"]

LABEL com.redhat.component="odh-must-gather" \
      name="odh-must-gather" \
      description="odh-must-gather" \
      summary="odh-must-gather" \
      io.k8s.display-name="odh-must-gather" \
      io.k8s.description="odh-must-gather"
