# To get kubectl CLI (1.33.3)
FROM registry.redhat.io/openshift4/ose-cli-rhel9@sha256:b36a4c332f05bd71c5315b6cfe38987809bae09c2865217e1c7240fa6bfd813b AS builder

FROM registry.redhat.io/openshift4/ose-must-gather-rhel9:v4.20.0@sha256:7e52f80a1c819c70227cfd94809e69ebb503283d383ae81d04518f487a0d9ff6
# copy original gather from base image to gather_original
RUN mv /usr/bin/gather /usr/bin/gather_original
# Copy kubectl from builder stage
COPY --from=builder /usr/bin/kubectl /usr/bin/kubectl
# copy all collection scripts to /usr/bin, including gather and subdirectories
COPY collection-scripts /usr/bin

ENTRYPOINT ["/usr/bin/gather"]

LABEL com.redhat.component="odh-must-gather" \
      name="odh-must-gather" \
      description="odh-must-gather" \
      summary="odh-must-gather" \
      io.k8s.display-name="odh-must-gather" \
      io.k8s.description="odh-must-gather"
